services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8000" # host:container
    command: npm run dev # hot reload
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
