###
GET http://localhost:8000

###

POST http://localhost:8000
Content-Type: application/json

{
    "name": "noah", 
    "location": "1234 street"
}

###

POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "noah",
    "email": "noah@xx.com",
    "password": "1234"
}

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "noah@xx.com",
    "password": "1234"
}

###

GET http://localhost:8000/test